/// A drop-in AG-UI + genui chat experience for Flutter.
///
/// Plug `AguiChat` into any Flutter app and it will:
///   • talk to an AG-UI-compatible agent backend over HTTP
///   • stream assistant text into chat bubbles
///   • render generative-UI surfaces (A2UI v0.9 ops) inline in the chat,
///     using the [Catalog] of widgets you provide
///
/// The widget owns the [SurfaceController], the AG-UI transport and the
/// [Conversation] for its lifetime — no setup beyond passing a `baseUrl`
/// and a `catalog`. Wrap it in whatever shell (Scaffold / AppBar / theme /
/// drawer) your app uses.
library;

import 'package:flutter/material.dart';
import 'package:genai_primitives/genai_primitives.dart' show ChatMessage;
import 'package:genui/genui.dart';

import 'agui_transport.dart';

/// A self-contained chat surface backed by an AG-UI agent.
///
/// Visuals are intentionally minimal and read entirely from
/// `Theme.of(context)` — drop it inside any themed `MaterialApp` and the
/// bubbles, input field and send button will follow the host theme.
class AguiChat extends StatefulWidget {
  const AguiChat({
    required this.baseUrl,
    required this.catalog,
    this.catalogDescription,
    this.hintText = 'Type a message…',
    this.sendButtonLabel = 'Send',
    super.key,
  });

  /// Base URL of the AG-UI agent endpoint, e.g. `http://localhost:8123`.
  /// The chat POSTs each turn to `"$baseUrl/"`.
  final String baseUrl;

  /// The genui [Catalog] of Flutter widgets the agent can render.
  /// Component names emitted by the agent must match item names in this catalog.
  final Catalog catalog;

  /// Optional free-text description of the catalog, shipped to the agent on
  /// every request via the AG-UI `context` field. Use this to teach the
  /// model the wire format and the props each component accepts.
  ///
  /// For fixed-schema backends (where the agent's tool already knows the
  /// schema), leave this null.
  final String? catalogDescription;

  /// Placeholder for the text input.
  final String hintText;

  /// Label for the send button.
  final String sendButtonLabel;

  @override
  State<AguiChat> createState() => _AguiChatState();
}

// ─── Message log model ──────────────────────────────────────────────────────

/// One entry in the chat log — text from either side, or an A2UI surface
/// generated by the agent.
sealed class _ChatItem {
  const _ChatItem();
}

class _UserBubble extends _ChatItem {
  const _UserBubble(this.text);
  final String text;
}

class _AssistantBubble extends _ChatItem {
  const _AssistantBubble(this.text);
  final String text;
}

class _SurfaceItem extends _ChatItem {
  const _SurfaceItem(this.surfaceId);
  final String surfaceId;
}

// ─── State ──────────────────────────────────────────────────────────────────

class _AguiChatState extends State<AguiChat> {
  late final SurfaceController _controller;
  late final AgUiTransport _transport;
  late final Conversation _conversation;
  final _textController = TextEditingController();
  final _scrollController = ScrollController();
  final List<_ChatItem> _items = [];
  bool _waiting = false;

  @override
  void initState() {
    super.initState();
    _controller = SurfaceController(catalogs: [widget.catalog]);
    _transport = AgUiTransport(
      baseUrl: widget.baseUrl,
      catalogDescription: widget.catalogDescription,
    );
    _conversation = Conversation(
      controller: _controller,
      transport: _transport,
    );
    _conversation.events.listen(_onEvent);
  }

  @override
  void dispose() {
    _conversation.dispose();
    _transport.dispose();
    _controller.dispose();
    _textController.dispose();
    _scrollController.dispose();
    super.dispose();
  }

  void _onEvent(ConversationEvent event) {
    setState(() {
      switch (event) {
        case ConversationContentReceived(:final text):
          _items.add(_AssistantBubble(text));
        case ConversationSurfaceAdded(:final surfaceId):
          if (!_items.any(
            (i) => i is _SurfaceItem && i.surfaceId == surfaceId,
          )) {
            _items.add(_SurfaceItem(surfaceId));
          }
        case ConversationSurfaceRemoved(:final surfaceId):
          _items.removeWhere(
            (i) => i is _SurfaceItem && i.surfaceId == surfaceId,
          );
        case ConversationWaiting():
          _waiting = true;
        case ConversationError(:final error):
          _items.add(_AssistantBubble('⚠️ $error'));
          _waiting = false;
        case ConversationComponentsUpdated():
          // Surface already on screen — auto-rebuilds via its SurfaceContext.
          break;
      }
    });
    if (event is! ConversationWaiting) {
      _waiting = false;
    }
    _scrollToEnd();
  }

  void _send() {
    final text = _textController.text.trim();
    if (text.isEmpty) return;
    setState(() {
      _items.add(_UserBubble(text));
      _waiting = true;
    });
    _textController.clear();
    _conversation.sendRequest(ChatMessage.user(text));
    _scrollToEnd();
  }

  void _scrollToEnd() {
    WidgetsBinding.instance.addPostFrameCallback((_) {
      if (!_scrollController.hasClients) return;
      _scrollController.animateTo(
        _scrollController.position.maxScrollExtent,
        duration: const Duration(milliseconds: 200),
        curve: Curves.easeOut,
      );
    });
  }

  @override
  Widget build(BuildContext context) {
    return Column(
      children: [
        Expanded(
          child: ListView.builder(
            controller: _scrollController,
            padding: const EdgeInsets.symmetric(vertical: 12, horizontal: 16),
            itemCount: _items.length + (_waiting ? 1 : 0),
            itemBuilder: (context, i) {
              if (i == _items.length) return const _ThinkingDots();
              final item = _items[i];
              return switch (item) {
                _UserBubble(:final text) => _Bubble(
                    text: text,
                    fromUser: true,
                  ),
                _AssistantBubble(:final text) => _Bubble(
                    text: text,
                    fromUser: false,
                  ),
                _SurfaceItem(:final surfaceId) => _SurfaceBubble(
                    surfaceContext: _controller.contextFor(surfaceId),
                  ),
              };
            },
          ),
        ),
        SafeArea(
          top: false,
          child: Padding(
            padding: const EdgeInsets.fromLTRB(12, 8, 12, 12),
            child: Row(
              children: [
                Expanded(
                  child: TextField(
                    controller: _textController,
                    onSubmitted: (_) => _send(),
                    // Use the consumer's bodyLarge style — Flutter's TextField
                    // otherwise falls back to titleMedium/subtitle1, which is
                    // a *title* style and often has a brand color baked in.
                    style: Theme.of(context).textTheme.bodyLarge,
                    decoration: InputDecoration(
                      hintText: widget.hintText,
                      isDense: true,
                    ),
                  ),
                ),
                const SizedBox(width: 8),
                // ElevatedButton works on both M2 and M3 themes — picks up
                // the themed primary color in both.
                ElevatedButton(
                  onPressed: _send,
                  child: Text(widget.sendButtonLabel),
                ),
              ],
            ),
          ),
        ),
      ],
    );
  }
}

// ─── Internal bubble widgets ────────────────────────────────────────────────

class _Bubble extends StatelessWidget {
  const _Bubble({required this.text, required this.fromUser});

  final String text;
  final bool fromUser;

  @override
  Widget build(BuildContext context) {
    final theme = Theme.of(context);
    final scheme = theme.colorScheme;
    // Colors come straight from the host theme — no opacity tricks, no
    // package-side opinions. Both tokens exist on M2 and M3 ThemeData.
    final bg = fromUser ? scheme.primary : theme.cardColor;
    final fg = fromUser ? scheme.onPrimary : scheme.onSurface;
    return Align(
      alignment: fromUser ? Alignment.centerRight : Alignment.centerLeft,
      child: Container(
        constraints: const BoxConstraints(maxWidth: 480),
        margin: const EdgeInsets.symmetric(vertical: 4),
        padding: const EdgeInsets.symmetric(horizontal: 12, vertical: 8),
        decoration: BoxDecoration(
          color: bg,
          borderRadius: BorderRadius.circular(12),
          // Border only on the neutral assistant bubble so it stays visible
          // when the theme's cardColor matches the scaffold background.
          border: fromUser ? null : Border.all(color: theme.dividerColor),
        ),
        child: Text(text, style: TextStyle(color: fg)),
      ),
    );
  }
}

class _SurfaceBubble extends StatelessWidget {
  const _SurfaceBubble({required this.surfaceContext});

  final SurfaceContext surfaceContext;

  @override
  Widget build(BuildContext context) {
    return Align(
      alignment: Alignment.centerLeft,
      child: Container(
        margin: const EdgeInsets.symmetric(vertical: 6),
        padding: const EdgeInsets.all(12),
        decoration: BoxDecoration(
          color: Theme.of(context).colorScheme.surface,
          border: Border.all(color: Theme.of(context).dividerColor),
          borderRadius: BorderRadius.circular(12),
        ),
        child: Surface(surfaceContext: surfaceContext),
      ),
    );
  }
}

class _ThinkingDots extends StatelessWidget {
  const _ThinkingDots();

  @override
  Widget build(BuildContext context) {
    return const Padding(
      padding: EdgeInsets.symmetric(vertical: 8, horizontal: 4),
      child: Align(
        alignment: Alignment.centerLeft,
        child: SizedBox(
          width: 24,
          height: 24,
          child: CircularProgressIndicator(strokeWidth: 2),
        ),
      ),
    );
  }
}
