/// A drop-in AG-UI + genui chat experience for Flutter.
///
/// Plug `AguiChat` into any Flutter app and it will:
///   • talk to an AG-UI-compatible agent backend over HTTP
///   • stream assistant text into chat bubbles
///   • render generative-UI surfaces (A2UI v0.9 ops) inline in the chat,
///     using the [Catalog] of widgets you provide
///
/// The widget owns the [SurfaceController], the AG-UI transport and the
/// [Conversation] for its lifetime — no setup beyond passing a `baseUrl`
/// and a `catalog`. Wrap it in whatever shell (Scaffold / AppBar / theme /
/// drawer) your app uses.
library;

import 'package:flutter/material.dart';
import 'package:genai_primitives/genai_primitives.dart' show ChatMessage;
import 'package:genui/genui.dart';

import 'agui_transport.dart';

/// A self-contained chat surface backed by an AG-UI agent.
///
/// Visuals are intentionally minimal and read entirely from
/// `Theme.of(context)` — drop it inside any themed `MaterialApp` and the
/// bubbles, input field and send button will follow the host theme.
class AguiChat extends StatefulWidget {
  const AguiChat({
    required this.baseUrl,
    required this.catalog,
    this.catalogDescription,
    this.hintText = 'Type a message…',
    this.sendButtonLabel = 'Send',
    this.emptyStateTitle,
    this.emptyStateSendButtonLabel = 'Send',
    this.uiRenderToolNames = const {},
    this.markdownA2uiLangTag,
    this.showAgentEvents = false,
    this.onStateChanged,
    super.key,
  });

  /// Base URL of the AG-UI agent endpoint, e.g. `http://localhost:8123`.
  /// The chat POSTs each turn to `"$baseUrl/"`.
  final String baseUrl;

  /// The genui [Catalog] of Flutter widgets the agent can render.
  /// Component names emitted by the agent must match item names in this catalog.
  final Catalog catalog;

  /// Optional free-text description of the catalog, shipped to the agent on
  /// every request via the AG-UI `context` field. Use this to teach the
  /// model the wire format and the props each component accepts.
  ///
  /// For fixed-schema backends (where the agent's tool already knows the
  /// schema), leave this null.
  final String? catalogDescription;

  /// Placeholder for the text input.
  final String hintText;

  /// Label for the send button while a conversation is in progress.
  final String sendButtonLabel;

  /// Optional headline shown above a centered input when the conversation has
  /// no messages yet. If null, the chat opens directly into the bubble list.
  final String? emptyStateTitle;

  /// Label for the send button shown in the empty state (before the first
  /// message is sent). Use this to set a call-to-action like "Create" while
  /// the in-conversation button reads "Send".
  final String emptyStateSendButtonLabel;

  /// Tool names whose ARGS carry an A2UI payload (the "ghost tool call"
  /// pattern). When the agent emits a tool call with one of these names, its
  /// args JSON is parsed as A2UI ops and a synthesized tool result is
  /// recorded in history.
  final Set<String> uiRenderToolNames;

  /// Fenced code-block language tag to intercept inside assistant text. When
  /// set (e.g. `'a2ui'`), the widget extracts ```<tag> ... ``` blocks from
  /// streamed assistant text, parses them as A2UI ops, and renders them as
  /// surfaces; the surrounding text is shown as a normal chat bubble. Null
  /// disables this path.
  final String? markdownA2uiLangTag;

  /// When true, AG-UI lifecycle events (tool calls, surface renders, etc.)
  /// are shown inline in the chat as small step rows, so the user sees what
  /// is happening instead of just a loader. Defaults to false.
  final bool showAgentEvents;

  /// Called whenever the agent's shared state changes (after STATE_SNAPSHOT
  /// or STATE_DELTA events). The backend is the source of truth: this
  /// callback only observes, it cannot mutate. The map is a fresh copy on
  /// every call.
  final ValueChanged<Map<String, dynamic>>? onStateChanged;

  @override
  State<AguiChat> createState() => _AguiChatState();
}

// ─── Message log model ──────────────────────────────────────────────────────

/// One entry in the chat log — text from either side, or an A2UI surface
/// generated by the agent.
sealed class _ChatItem {
  const _ChatItem();
}

class _UserBubble extends _ChatItem {
  const _UserBubble(this.text);

  final String text;
}

class _AssistantBubble extends _ChatItem {
  const _AssistantBubble(this.text);

  final String text;
}

class _SurfaceItem extends _ChatItem {
  const _SurfaceItem(this.surfaceId);

  final String surfaceId;
}

class _EventItem extends _ChatItem {
  const _EventItem(this.text);

  final String text;
}

// ─── State ──────────────────────────────────────────────────────────────────

class _AguiChatState extends State<AguiChat> {
  late final SurfaceController _controller;
  late final AgUiTransport _transport;
  late final Conversation _conversation;
  final _textController = TextEditingController();
  final _scrollController = ScrollController();
  final List<_ChatItem> _items = [];
  bool _waiting = false;

  @override
  void initState() {
    super.initState();
    _controller = SurfaceController(catalogs: [widget.catalog]);
    _transport = AgUiTransport(
      baseUrl: widget.baseUrl,
      catalogDescription: widget.catalogDescription,
      uiRenderToolNames: widget.uiRenderToolNames,
      markdownA2uiLangTag: widget.markdownA2uiLangTag,
    );
    _conversation = Conversation(controller: _controller, transport: _transport);
    _conversation.events.listen(_onEvent);
    // genUI's Conversation tracks waiting state on its `state` notifier (set
    // to false in a try/finally around transport.sendRequest). Events alone
    // are not enough — a click that only fires updateDataModel ops emits no
    // ConversationComponentsUpdated, so listening to events leaves the
    // loader spinning. The notifier is the authoritative source.
    _conversation.state.addListener(_onConversationStateChanged);
    if (widget.showAgentEvents) {
      _transport.agentEvents.listen(_onAgentEvent);
    }
    if (widget.onStateChanged != null) {
      _transport.state.addListener(_onStateChanged);
    }
  }

  void _onConversationStateChanged() {
    final isWaiting = _conversation.state.value.isWaiting;
    if (isWaiting != _waiting) {
      setState(() => _waiting = isWaiting);
      if (!isWaiting) _scrollToEnd();
    }
  }

  void _onAgentEvent(String text) {
    setState(() => _items.add(_EventItem(text)));
    _scrollToEnd();
  }

  void _onStateChanged() {
    widget.onStateChanged?.call(Map<String, dynamic>.from(_transport.state.value));
  }

  @override
  void dispose() {
    if (widget.onStateChanged != null) {
      _transport.state.removeListener(_onStateChanged);
    }
    _conversation.state.removeListener(_onConversationStateChanged);
    _conversation.dispose();
    _transport.dispose();
    _controller.dispose();
    _textController.dispose();
    _scrollController.dispose();
    super.dispose();
  }

  void _onEvent(ConversationEvent event) {
    setState(() {
      switch (event) {
        case ConversationContentReceived(:final text):
          _items.add(_AssistantBubble(text));
        case ConversationSurfaceAdded(:final surfaceId):
          if (!_items.any((i) => i is _SurfaceItem && i.surfaceId == surfaceId)) {
            _items.add(_SurfaceItem(surfaceId));
          }
        case ConversationSurfaceRemoved(:final surfaceId):
          _items.removeWhere((i) => i is _SurfaceItem && i.surfaceId == surfaceId);
        case ConversationError(:final error):
          _items.add(_AssistantBubble('⚠️ $error'));
        case ConversationWaiting():
        case ConversationComponentsUpdated():
          // ConversationWaiting / waiting-cleared transitions are handled
          // by the conversation state notifier listener — _onEvent doesn't
          // touch _waiting. ComponentsUpdated requires no state change here:
          // the on-screen Surface auto-rebuilds via its SurfaceContext.
          break;
      }
    });
    _scrollToEnd();
  }

  void _send() {
    final text = _textController.text.trim();
    if (text.isEmpty) return;
    setState(() {
      _items.add(_UserBubble(text));
      _waiting = true;
    });
    _textController.clear();
    _conversation.sendRequest(ChatMessage.user(text));
    _scrollToEnd();
  }

  void _scrollToEnd() {
    WidgetsBinding.instance.addPostFrameCallback((_) {
      if (!_scrollController.hasClients) return;
      _scrollController.animateTo(
        _scrollController.position.maxScrollExtent,
        duration: const Duration(milliseconds: 200),
        curve: Curves.easeOut,
      );
    });
  }

  @override
  Widget build(BuildContext context) {
    final showEmptyState = widget.emptyStateTitle != null && _items.isEmpty && !_waiting;
    if (showEmptyState) return _buildEmptyState(context);
    return _buildChat(context);
  }

  Widget _buildEmptyState(BuildContext context) {
    final theme = Theme.of(context);
    return SafeArea(
      child: Center(
        child: SingleChildScrollView(
          padding: const EdgeInsets.all(24),
          child: ConstrainedBox(
            constraints: const BoxConstraints(maxWidth: 560),
            child: Column(
              mainAxisSize: MainAxisSize.min,
              crossAxisAlignment: CrossAxisAlignment.stretch,
              children: [
                Text(
                  widget.emptyStateTitle!,
                  textAlign: TextAlign.center,
                  style: theme.textTheme.headlineMedium?.copyWith(
                    color: theme.colorScheme.onSurface.withValues(alpha: 0.55),
                    fontWeight: FontWeight.w500,
                  ),
                ),
                const SizedBox(height: 28),
                _PillInput(
                  controller: _textController,
                  hintText: widget.hintText,
                  sendLabel: widget.emptyStateSendButtonLabel,
                  onSend: _send,
                ),
              ],
            ),
          ),
        ),
      ),
    );
  }

  Widget _buildChat(BuildContext context) {
    return Column(
      children: [
        Expanded(
          child: ListView.builder(
            controller: _scrollController,
            padding: const EdgeInsets.symmetric(vertical: 12, horizontal: 16),
            itemCount: _items.length + (_waiting ? 1 : 0),
            itemBuilder: (context, i) {
              if (i == _items.length) return const _ThinkingDots();
              final item = _items[i];
              return switch (item) {
                _UserBubble(:final text) => _Bubble(text: text, fromUser: true),
                _AssistantBubble(:final text) => _Bubble(text: text, fromUser: false),
                _SurfaceItem(:final surfaceId) => _SurfaceBubble(surfaceContext: _controller.contextFor(surfaceId)),
                _EventItem(:final text) => _EventRow(text: text),
              };
            },
          ),
        ),
        SafeArea(
          top: false,
          child: Padding(
            padding: const EdgeInsets.fromLTRB(12, 8, 12, 12),
            child: _PillInput(controller: _textController, hintText: '', sendLabel: 'Send', onSend: _send),
          ),
        ),
      ],
    );
  }
}

// ─── Internal bubble widgets ────────────────────────────────────────────────

class _Bubble extends StatelessWidget {
  const _Bubble({required this.text, required this.fromUser});

  final String text;
  final bool fromUser;

  @override
  Widget build(BuildContext context) {
    final theme = Theme.of(context);
    final scheme = theme.colorScheme;
    // Colors come straight from the host theme — no opacity tricks, no
    // package-side opinions. Both tokens exist on M2 and M3 ThemeData.
    final bg = fromUser ? scheme.primary : theme.cardColor;
    final fg = fromUser ? scheme.onPrimary : scheme.onSurface;
    return Align(
      alignment: fromUser ? Alignment.centerRight : Alignment.centerLeft,
      child: Container(
        constraints: const BoxConstraints(maxWidth: 480),
        margin: const EdgeInsets.symmetric(vertical: 4),
        padding: const EdgeInsets.symmetric(horizontal: 12, vertical: 8),
        decoration: BoxDecoration(
          color: bg,
          borderRadius: BorderRadius.circular(12),
          // Border only on the neutral assistant bubble so it stays visible
          // when the theme's cardColor matches the scaffold background.
          border: fromUser ? null : Border.all(color: theme.dividerColor),
        ),
        child: Text(text, style: TextStyle(color: fg)),
      ),
    );
  }
}

class _SurfaceBubble extends StatelessWidget {
  const _SurfaceBubble({required this.surfaceContext});

  final SurfaceContext surfaceContext;

  @override
  Widget build(BuildContext context) {
    return Align(
      alignment: Alignment.centerLeft,
      child: Container(
        margin: const EdgeInsets.symmetric(vertical: 6),
        padding: const EdgeInsets.all(12),
        decoration: BoxDecoration(
          color: Theme.of(context).colorScheme.surface,
          border: Border.all(color: Theme.of(context).dividerColor),
          borderRadius: BorderRadius.circular(12),
        ),
        child: Surface(surfaceContext: surfaceContext),
      ),
    );
  }
}

class _EventRow extends StatelessWidget {
  const _EventRow({required this.text});

  final String text;

  @override
  Widget build(BuildContext context) {
    final theme = Theme.of(context);
    final mutedColor = theme.colorScheme.onSurface.withValues(alpha: 0.55);
    return Padding(
      padding: const EdgeInsets.symmetric(vertical: 6, horizontal: 4),
      child: Row(
        mainAxisSize: MainAxisSize.min,
        crossAxisAlignment: CrossAxisAlignment.center,
        children: [
          Icon(Icons.circle, size: 6, color: mutedColor),
          const SizedBox(width: 10),
          Flexible(
            child: Text(
              text,
              style: theme.textTheme.bodySmall?.copyWith(color: mutedColor, fontStyle: FontStyle.italic),
            ),
          ),
        ],
      ),
    );
  }
}

class _PillInput extends StatelessWidget {
  const _PillInput({required this.controller, required this.hintText, required this.sendLabel, required this.onSend});

  final TextEditingController controller;
  final String hintText;
  final String sendLabel;
  final VoidCallback onSend;

  @override
  Widget build(BuildContext context) {
    final theme = Theme.of(context);
    final scheme = theme.colorScheme;
    final buttonBg = Color.alphaBlend(scheme.onSurface.withValues(alpha: 0.08), scheme.surface);
    return Container(
      decoration: BoxDecoration(
        color: scheme.surface,
        borderRadius: BorderRadius.circular(32),
        border: Border.all(color: theme.dividerColor),
      ),
      padding: const EdgeInsets.fromLTRB(20, 6, 6, 6),
      child: Row(
        children: [
          Expanded(
            child: TextField(
              controller: controller,
              onSubmitted: (_) => onSend(),
              style: theme.textTheme.bodyLarge,
              // Strip the host theme's input border — the pill container
              // already provides the border, and an OutlineInputBorder from
              // the host theme would draw a second visible rectangle inside.
              decoration: InputDecoration(
                hintText: hintText,
                hintStyle: theme.textTheme.bodyLarge?.copyWith(color: scheme.onSurface.withValues(alpha: 0.45)),
                border: InputBorder.none,
                enabledBorder: InputBorder.none,
                focusedBorder: InputBorder.none,
                isDense: true,
                // contentPadding: const EdgeInsets.symmetric(vertical: 14),
              ),
            ),
          ),
          const SizedBox(width: 8),
          TextButton(
            onPressed: onSend,
            style: TextButton.styleFrom(
              backgroundColor: buttonBg,
              foregroundColor: scheme.onSurface,
              padding: const EdgeInsets.symmetric(horizontal: 20, vertical: 14),
              shape: const StadiumBorder(),
              textStyle: const TextStyle(fontWeight: FontWeight.w500),
            ),
            child: Text(sendLabel),
          ),
        ],
      ),
    );
  }
}

class _ThinkingDots extends StatelessWidget {
  const _ThinkingDots();

  @override
  Widget build(BuildContext context) {
    return const Padding(
      padding: EdgeInsets.symmetric(vertical: 8, horizontal: 4),
      child: Align(
        alignment: Alignment.centerLeft,
        child: SizedBox(width: 24, height: 24, child: CircularProgressIndicator(strokeWidth: 2)),
      ),
    );
  }
}
